### ISSUE TITLE
manual changes on the database are not synced with the FTS table

### ISSUE THREAD

**Issue by nczirjak-acdh** [acdh-oeaw/arche-core#16]
I discovered this issue while i changed the GUI code, to support the ontology V2 and the TopCollections.

The manually changed rdf:type -> acdh:TopCollections are not synced to the Full text search Db table, and the GUI is using this table for the search view.

**Comment by zozlak** [comment]
At the moment the sync is done by the arche-core's PHP code which means it's only triggered by REST API calls. All the changes made directly on the database do not update the FTS table and make it our of sync. This is definitely wrong. It should be solved by moving the sync logic from the PHP code into the database trigger(s) so it's done the same way metadata history is maintained.

**Comment by zozlak** [comment]
The tricky part is there is some yaml-config-based logic in the PHP code but as we don't really use it now, we can probably leave without it.

**Comment by zozlak** [comment]
Fixed by c16a0a5d7c0d2b17e333e0cd25027d2539b05125 and c5046a348d6a31998005eb976a32482f1c909afa
