### ISSUE TITLE
Provide spatial indexing

### ISSUE THREAD

**Issue by zozlak** [acdh-oeaw/arche-core#18]
Arche-core uses Postgresql as a backend, so adding spatial indexing and search with Postgis shouldn't be a rocket science. This would require:

* Adding a separate table storing the spatial objects similarly to how it's done for the full text search.
* Agree on the spatial data input format (WKT?)
* Define a way of defining a given RDF datatype/predicate contains spatial data (clearly yet another configuration property)
* Add spatial search operators to arche-lib similarly to already existing full text search operator.

To decide (@csae8092) - what kind of operators do we need. I would say intersection should be enough. If someone wants more fancy ones, (s)he may use an SQL query with all the goodies Postgis provides.

(see https://redmine.acdh.oeaw.ac.at/issues/19100)

**Comment by csae8092** [comment]
* WKT is fine and we have already a property (in use) https://github.com/acdh-oeaw/arche-schema/blob/master/acdh-schema.owl#L2373

* as for the search operators I can think of use case for for matching resources for a given POINT or POLYON
  * https://postgis.net/docs/manual-dev/ST_ContainsProperly.html
  * https://postgis.net/docs/manual-dev/ST_Contains.html

I pass into a query a Polygon -> give me all resources either fully in this polygon | give me all resources intersecting this polygon
I pass into a query a Point -> give me all resources this point intersects with

**Comment by zozlak** [comment]
Do you think contains is more intuitive than intersects?
I would argue that "contains" raises the issue of what should be contained in what (search geometry in repository object geometry or other way round) and depending on particular search users may expect different behavior. Intersection doesn't have this ambiguity.

Of course we can also create three operators, let's say `&&` (intersects), `&>&` (right contained in left), `&<&` (left contained in right).

**Comment by csae8092** [comment]
> Of course we can also create three operators, let's say && (intersects), &>& (right contained in left), &<& (left contained in right).

perfect

**Comment by zozlak** [comment]
Implemented in 04e66eb130c8484da30ac55ba245bddfe4d7c875 (arche-core) and  [25c61b55411264f9b2eaa27686139272108a052f](https://github.com/acdh-oeaw/arche-lib/commit/25c61b55411264f9b2eaa27686139272108a052f) in arche-lib
