### ISSUE TITLE
Safari, dropdown fields stopped working

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/arche-core#21]
On Safari (15.0 (16612.1.29.41.4, 16612)) on MacOS the dropdown fields are no longer accessible, e.g. no text can be entered. This is from console:
![Bildschirmfoto 2021-10-12 um 10 00 22](https://user-images.githubusercontent.com/11441262/136917033-4721a4da-9860-44a3-9c00-7adf55f3fb2f.png)

**Comment by zozlak** [comment]
I guess this error belongs to https://github.com/acdh-oeaw/arche-gui

**Comment by zozlak** [comment]
I think Norbert manages GUI issues in the Redmine.

**Comment by martinantonmueller** [comment]
Ooops, that is where this issue went! I'm awfully sorry, that was for APIS and not Arche. Can we delete it?
